channels:
  - conda-forge
dependencies:
  # core
  - openff-interchange >=0.3.18
  - openff-models
  - pooch
  - xtb-python
  # examples
  - nglview
  # docs
  - nbsphinx
  - sphinx
  # tests
  - pytest
  - pytest-xdist
  # viz
  - pymol-open-source
  - pip:
    - nbsphinx-link >=1.3.1
